services:
  docker-rss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-rss
    ports:
      - "8083:8083"
    environment:
      - UPDATE_SCHEDULE=* * * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
