services:
  docker-rss:
    image: vector450/docker-rss:latest
    container_name: docker-rss
    ports:
      - "8083:8083"
    environment:
      - TZ=Asia/Singapore
      - UPDATE_SCHEDULE=0 * * * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
